[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.com"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
